### ISSUE TITLE
Remove color attribute from hollow blocks

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#79]
I feel that `Hollow Blocks` should be able to be colored, so that we can do things with colored tiles that only can have that color of thing go on them, this would allow paths for certain blocks and allow for more intricate moves.

**Comment by grady404** [comment]
I don't think including colored tiles and colored hollow blocks is a very good idea.
- Both of these mechanics make the design of the game seem overcomplicated.
- The colored tiles won't really be very aesthetically pleasing.
- Since a block of the wrong type will simply stop upon reaching a colored tile, levels involving these tiles might be prone to "cheat" solutions, and designing these levels will be difficult.
- If we have colored hollow blocks, the user will be very confused as to why they are blue/colored (thinking that they may be colored for a reason), until they first encounter colored tiles much later in the game.
- If the wildcard block can be thought of as having all four colors, then the hollow block can be thought of as having none of the four colors, and in that case even if we do implement colored tiles hollow blocks simply shouldn't be able to pass over them at all.
